blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/tanabee/issue-automation-sample/issues/new?template=issue.md&projects=tanabee/issue-automation-sample/1&labels=enhancement
